services:
  shakaplayerthumbnail:
    build:
      context: .  
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    networks:
      - thumbnail-network   
    environment:
      - access_key=Qqt3KMXNlK4iCKqPhgEd
      - secret_key=Kncx7QKlHyaN1rmbRRrAqDvDLGhGt8IAPdwhyjg6
      - service_url=http://10.13.111.3
  nginx:
    build:
      context: .     
      dockerfile: NginxDockerfile
    depends_on:
      - shakaplayerthumbnail
    ports:
      - "79:79"
    networks:
      - thumbnail-network

networks:
  thumbnail-network:
    driver: host

