services:
  shakaplayerthumbnail:
    build:
      context: .  
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    networks:
      - thumbnail-network   
    environment:
      - access_key=Qqt3KMXNlK4iCKqPhgEd
      - secret_key=Kncx7QKlHyaN1rmbRRrAqDvDLGhGt8IAPdwhyjg6
      - service_url=http://10.13.111.3
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "79:79"
    volumes:
      - ./minio.conf:/etc/nginx/conf.d/default.conf
    networks:
      - thumbnail-network
    depends_on:
      - shakaplayerthumbnail
networks:
  thumbnail-network:
    driver: bridge

