services:
  shakaplayerthumbnail:
    build:
      context: .
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    environment:
      - access_key=OyNWsqRLkvWYokHckqm0
      - secret_key=Ia08qOvDO5guqma1dCp3p8vAXu3S8Jz0MnDbMzHU
      - service_url=https://minio.john-group.org
    networks:
      - thumbnail-network
    ports:
      - "5006:5006"
    volumes:
      - ffmpeg-data:/app/data  # Mount the volume for FFmpeg files


networks:
  thumbnail-network:
    driver: bridge

volumes:
  ffmpeg-data:
    driver: local

