services:
  shakaplayerthumbnail:
    build:
      context: .
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    environment:
      - access_key=b8uGptYNhcPKikLNq7k1
      - secret_key=SrisPrHVFVbnaYK8xb3BJcSBGL14mB8IyvdiBwbU
      - service_url=https://minio.john-group.org
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - COMPlus_ThreadPool_ForceMinWorkerThreads=200  
    networks:
      - thumbnail-network
    ports:
      - "5006:5006"
    volumes:
      - thumbnail-data:/etc/data
    deploy:
      resources:
        limits:
          cpus: '4.0'  # Adjust based on available CPU cores (use 4 cores)
          memory: 4g  # Limit memory usage to 4 GB
        reservations:
          cpus: '2.0'  # Reserve at least 2 CPU cores
          memory: 2g  # Reserve 2 GB memory

  thumbnail-nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    depends_on:
      - shakaplayerthumbnail
    ports:
      - "80:80"
    networks:
      - thumbnail-network
    volumes:
      - thumbnail-data:/etc/data
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Assign 2 CPU cores
          memory: 2g  # Limit memory usage to 2 GB
        reservations:
          cpus: '1.0'  # Reserve at least 1 CPU core
          memory: 1g  # Reserve 1 GB memory

networks:
  thumbnail-network:
    driver: bridge

volumes:
  thumbnail-data:
    driver: local
