services:
  shakaplayerthumbnail:
    build:
      context: .
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    environment:
      - access_key=Qqt3KMXNlK4iCKqPhgEd
      - secret_key=Kncx7QKlHyaN1rmbRRrAqDvDLGhGt8IAPdwhyjg6
      - service_url=http://10.13.111.3
    networks:
      - thumbnail-network
    ports:
      - "5006:5006"
  thumbnail-nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    depends_on:
      - shakaplayerthumbnail
    ports:
      - "80:80"
    networks:
      - thumbnail-network

networks:
  thumbnail-network:
    driver: bridge
