services:
  shakaplayerthumbnail:
    build:
      context: .
      dockerfile: ShakaPlayerThumbnail/Dockerfile
    environment:
      - access_key=b8uGptYNhcPKikLNq7k1
      - secret_key=SrisPrHVFVbnaYK8xb3BJcSBGL14mB8IyvdiBwbU
      - service_url=https://minio.john-group.org
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - COMPlus_ThreadPool_ForceMinWorkerThreads=200  
    networks:
      - thumbnail-network
    ports:
      - "5006:5006"
    volumes:
      - thumbnail-data:/etc/data
    deploy:
      resources:
        limits:
          cpus: '12.0' 
          memory: 2g
        reservations:
          cpus: '2.0'  
          memory: 0g
  thumbnail-nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    depends_on:
      - shakaplayerthumbnail
    ports:
      - "80:80"
    networks:
      - thumbnail-network
    volumes:
      - thumbnail-data:/etc/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g 
        reservations:
          cpus: '1.0'  
          memory: 1g  
networks:
  thumbnail-network:
    driver: bridge

volumes:
  thumbnail-data:
    driver: local
